version: 1
services:
  - type: web
    name: vid-downloader-pro
    env: node
    plan: free
    buildCommand: YOUTUBE_DL_SKIP_DOWNLOAD=true npm install --ignore-scripts --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        generateValue: false # This tells Render to ask for it if missing
      - key: YOUTUBE_DL_SKIP_DOWNLOAD
        value: "true"
      - key: PORT
        value: 10000
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        generateValue: false # Prompt for value in Render
      - key: SMTP_PASS
        generateValue: false # Prompt for value in Render
      - key: CONTACT_EMAIL
        generateValue: false # Prompt for value in Render
