services:
  - type: web
    name: vid-downloader-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will prompt you to enter the URL manually during setup
      - key: PORT
        value: 10000
