version: 1
services:
  - type: web
    name: vid-downloader-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        generateValue: false # This tells Render to ask for it if missing
      - key: YOUTUBE_DL_SKIP_DOWNLOAD
        value: "true"
      - key: PORT
        value: 10000
